### ISSUE TITLE
@media print rule needed in app-header-layout?

### ISSUE THREAD

**Issue by robrez** [PolymerLabs/app-layout#110]
when using browser's native print, `position: fixed` header inside `app-header-layout` shows up.. in its current position w/ regard to document scroll pos.

eg:
```
  content
  content
--------------
Hai toolbar
--------------
  content
```

This rule added app-header-layout may be a good start..
```
  @media print {
    :host > ::content > app-header,
    :host > ::content > [underlay-content] {
      position: absolute;
    }
  }
```

**Comment by blasten** [comment]
Your content is in the light DOM, so you could do this:

```css
 @media print {
     app-header,
    [underlay-content] {
      position: absolute;
    }
  }
```
